DROP TABLE IF EXISTS roles CASCADE;

CREATE TABLE roles
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name VARCHAR(50) UNIQUE
);

CREATE INDEX idx_roles_name ON roles (role_name);

INSERT INTO roles (role_name) VALUES ('ADMIN'), ('DIRECTOR'), ('USER');