DROP TABLE IF EXISTS pnms CASCADE;

CREATE TABLE pnms
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name   VARCHAR(50)  NOT NULL,
    last_name    VARCHAR(50)  NOT NULL,
    class_year   VARCHAR(20)  NOT NULL CHECK (class_year IN ('Freshman', 'Sophomore', 'Junior', 'Senior', 'Super Senior')),
    status       VARCHAR(10)           CHECK (status IN ('delta', 'sigma', 'phi')),
    housing_type VARCHAR(10)  NOT NULL CHECK (housing_type IN ('on_campus', 'off_campus'))
);